name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.3

      - name: Run ruff for linting
        run: |
          pip install ruff
          ruff check .

      - name: Convert data.xlsx to data.csv
        run: |
          python -c "import pandas as pd; df = pd.read_excel('data.xlsx'); df.to_csv('data.csv', index=False)"

      - name: Run execute.py and output result.json
        run: |
          python execute.py > result.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          # Assuming index.html is in root and will be served
          # Alternatively, you can specify a subdirectory if needed
